apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "things.fullname" . | trunc 54 | trimSuffix "-" | printf "%s-syncd-db" }}
  namespace: {{ .Release.Namespace }}
  {{- with include "things.labels" . }}
  labels:
    {{ . |nindent 4 }}
  {{- end }}
data:
  schema.sql: |
    create schema if not exists things;

    create table if not exists things.things (
      id          varchar not null primary key,
      owner       varchar not null,
      name        varchar not null,
      actioncount integer default 0,
      version     text    not null
    );
    create index if not exists things__id_version_index on things.things (id, version);

    create table if not exists things.actions (
      thing    varchar not null,
      action   varchar not null,
      time     integer not null,
      sequence integer not null,
      primary key (thing, sequence)
    );
