// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/syncd.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	Error_SERVER_ERROR     Error = 0
	Error_MALFORMED_RECORD Error = 1
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "SERVER_ERROR",
		1: "MALFORMED_RECORD",
	}
	Error_value = map[string]int32{
		"SERVER_ERROR":     0,
		"MALFORMED_RECORD": 1,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_api_syncd_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_api_syncd_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_api_syncd_proto_rawDescGZIP(), []int{0}
}

type DataType int32

const (
	DataType_UINT   DataType = 0 // encoded as uint64
	DataType_INT    DataType = 1 // encoded as sint64
	DataType_FLOAT  DataType = 2 // encoded as double
	DataType_BOOL   DataType = 3 // encoded as bool
	DataType_STRING DataType = 4 // encoded as string
	DataType_BYTES  DataType = 5 // encoded as bytes
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "UINT",
		1: "INT",
		2: "FLOAT",
		3: "BOOL",
		4: "STRING",
		5: "BYTES",
	}
	DataType_value = map[string]int32{
		"UINT":   0,
		"INT":    1,
		"FLOAT":  2,
		"BOOL":   3,
		"STRING": 4,
		"BYTES":  5,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_syncd_proto_enumTypes[1].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_api_syncd_proto_enumTypes[1]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_api_syncd_proto_rawDescGZIP(), []int{1}
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields map[string]*Data `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_syncd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_syncd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_syncd_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetFields() map[string]*Data {
	if x != nil {
		return x.Fields
	}
	return nil
}

type RecordStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         *Data   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version    *Data   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Error      *uint32 `protobuf:"varint,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	ErrorField *string `protobuf:"bytes,4,opt,name=error_field,json=errorField,proto3,oneof" json:"error_field,omitempty"`
}

func (x *RecordStatus) Reset() {
	*x = RecordStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_syncd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordStatus) ProtoMessage() {}

func (x *RecordStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_syncd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordStatus.ProtoReflect.Descriptor instead.
func (*RecordStatus) Descriptor() ([]byte, []int) {
	return file_api_syncd_proto_rawDescGZIP(), []int{1}
}

func (x *RecordStatus) GetId() *Data {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RecordStatus) GetVersion() *Data {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *RecordStatus) GetError() uint32 {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return 0
}

func (x *RecordStatus) GetErrorField() string {
	if x != nil && x.ErrorField != nil {
		return *x.ErrorField
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type DataType `protobuf:"varint,1,opt,name=type,proto3,enum=syncd.DataType" json:"type,omitempty"`
	// Types that are assignable to Value:
	//
	//	*Data_Uint
	//	*Data_Int
	//	*Data_Float
	//	*Data_Bool
	//	*Data_String_
	//	*Data_Bytes
	Value isData_Value `protobuf_oneof:"value"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_syncd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_syncd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_api_syncd_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_UINT
}

func (m *Data) GetValue() isData_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Data) GetUint() uint64 {
	if x, ok := x.GetValue().(*Data_Uint); ok {
		return x.Uint
	}
	return 0
}

func (x *Data) GetInt() int64 {
	if x, ok := x.GetValue().(*Data_Int); ok {
		return x.Int
	}
	return 0
}

func (x *Data) GetFloat() float64 {
	if x, ok := x.GetValue().(*Data_Float); ok {
		return x.Float
	}
	return 0
}

func (x *Data) GetBool() bool {
	if x, ok := x.GetValue().(*Data_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *Data) GetString_() string {
	if x, ok := x.GetValue().(*Data_String_); ok {
		return x.String_
	}
	return ""
}

func (x *Data) GetBytes() []byte {
	if x, ok := x.GetValue().(*Data_Bytes); ok {
		return x.Bytes
	}
	return nil
}

type isData_Value interface {
	isData_Value()
}

type Data_Uint struct {
	Uint uint64 `protobuf:"varint,2,opt,name=uint,proto3,oneof"`
}

type Data_Int struct {
	Int int64 `protobuf:"zigzag64,3,opt,name=int,proto3,oneof"`
}

type Data_Float struct {
	Float float64 `protobuf:"fixed64,4,opt,name=float,proto3,oneof"`
}

type Data_Bool struct {
	Bool bool `protobuf:"varint,5,opt,name=bool,proto3,oneof"`
}

type Data_String_ struct {
	String_ string `protobuf:"bytes,6,opt,name=string,proto3,oneof"`
}

type Data_Bytes struct {
	Bytes []byte `protobuf:"bytes,7,opt,name=bytes,proto3,oneof"`
}

func (*Data_Uint) isData_Value() {}

func (*Data_Int) isData_Value() {}

func (*Data_Float) isData_Value() {}

func (*Data_Bool) isData_Value() {}

func (*Data_String_) isData_Value() {}

func (*Data_Bytes) isData_Value() {}

var File_api_syncd_proto protoreflect.FileDescriptor

var file_api_syncd_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x73, 0x79, 0x6e, 0x63, 0x64, 0x22, 0x83, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x46, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x64, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xad,
	0x01, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x79,
	0x6e, 0x63, 0x64, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x73, 0x79, 0x6e, 0x63, 0x64, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x24,
	0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0e,
	0x0a, 0x0c, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0xbe,
	0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x64, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x04,
	0x75, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x04, 0x75, 0x69,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x12, 0x48,
	0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x14,
	0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04,
	0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x16,
	0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a,
	0x2f, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56,
	0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x41,
	0x4c, 0x46, 0x4f, 0x52, 0x4d, 0x45, 0x44, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x10, 0x01,
	0x2a, 0x49, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x55, 0x49, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x54, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f,
	0x4f, 0x4c, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x04,
	0x12, 0x09, 0x0a, 0x05, 0x42, 0x59, 0x54, 0x45, 0x53, 0x10, 0x05, 0x32, 0x3a, 0x0a, 0x08, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x12,
	0x0d, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x13,
	0x2e, 0x73, 0x79, 0x6e, 0x63, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x28, 0x01, 0x30, 0x01, 0x32, 0x3b, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x04, 0x50, 0x75, 0x6c, 0x6c, 0x12, 0x13, 0x2e, 0x73,
	0x79, 0x6e, 0x63, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x1a, 0x0d, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x2d, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x73, 0x79, 0x6e,
	0x63, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_syncd_proto_rawDescOnce sync.Once
	file_api_syncd_proto_rawDescData = file_api_syncd_proto_rawDesc
)

func file_api_syncd_proto_rawDescGZIP() []byte {
	file_api_syncd_proto_rawDescOnce.Do(func() {
		file_api_syncd_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_syncd_proto_rawDescData)
	})
	return file_api_syncd_proto_rawDescData
}

var file_api_syncd_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_syncd_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_syncd_proto_goTypes = []interface{}{
	(Error)(0),           // 0: syncd.Error
	(DataType)(0),        // 1: syncd.DataType
	(*Record)(nil),       // 2: syncd.Record
	(*RecordStatus)(nil), // 3: syncd.RecordStatus
	(*Data)(nil),         // 4: syncd.Data
	nil,                  // 5: syncd.Record.FieldsEntry
}
var file_api_syncd_proto_depIdxs = []int32{
	5, // 0: syncd.Record.fields:type_name -> syncd.Record.FieldsEntry
	4, // 1: syncd.RecordStatus.id:type_name -> syncd.Data
	4, // 2: syncd.RecordStatus.version:type_name -> syncd.Data
	1, // 3: syncd.Data.type:type_name -> syncd.DataType
	4, // 4: syncd.Record.FieldsEntry.value:type_name -> syncd.Data
	2, // 5: syncd.Consumer.Push:input_type -> syncd.Record
	3, // 6: syncd.Publisher.Pull:input_type -> syncd.RecordStatus
	3, // 7: syncd.Consumer.Push:output_type -> syncd.RecordStatus
	2, // 8: syncd.Publisher.Pull:output_type -> syncd.Record
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_syncd_proto_init() }
func file_api_syncd_proto_init() {
	if File_api_syncd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_syncd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_syncd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_syncd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_syncd_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_api_syncd_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Data_Uint)(nil),
		(*Data_Int)(nil),
		(*Data_Float)(nil),
		(*Data_Bool)(nil),
		(*Data_String_)(nil),
		(*Data_Bytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_syncd_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_syncd_proto_goTypes,
		DependencyIndexes: file_api_syncd_proto_depIdxs,
		EnumInfos:         file_api_syncd_proto_enumTypes,
		MessageInfos:      file_api_syncd_proto_msgTypes,
	}.Build()
	File_api_syncd_proto = out.File
	file_api_syncd_proto_rawDesc = nil
	file_api_syncd_proto_goTypes = nil
	file_api_syncd_proto_depIdxs = nil
}
