{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "syncd-server.fullname" . }}
  labels:
    {{- include "syncd-server.labels" . | nindent 4 }}
data:
  server.yaml: |
    {{- with .Values.global.logging }}
    logging:
    {{- toYaml . |nindent 6 }}
    {{- end }}

    server:
      listen: ":8080"
      metrics:
        listen: ":8081"
      tls: {}
      auth:
        {{- with .Values.global.auth.preSharedKey }}
        {{- include "syncd-server.preShareKey" . |nindent 8 }}
        {{- else }}
        {{- with .Values.auth.preSharedKey }}
        {{- include "syncd-server.preShareKey" . |nindent 8 }}
        {{- end }}
        {{- end }}

    graph:
      postgres:
        syncTable:
          name: {{ printf "%s.%s" .Values.global.graph.source.postgres.schema .Values.global.graph.source.postgres.sequenceTable }}
        sequenceTable:
          name: {{ printf "%s.%s" .Values.global.graph.source.postgres.schema .Values.global.graph.source.postgres.sequenceTable }}
        connection:
          fromEnv: {{ .Values.global.graph.source.postgres.connection.fromPreExistingSecret.key }}
      models:
        {{- with .Values.graph.models }}
        {{- toYaml . | nindent 8 }}
        {{- else }}
        {{- with .Values.global.graph.models }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
    {{- end }}
