{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncd-server.fullname" . }}
  labels:
    {{- include "syncd-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "syncd-server.selectorLabels" . | nindent 4 }}
{{- end }}