global:
  postgresql:
    auth:
      username: syncd
      database: syncd

postgresql:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      labels:
        release: kube-prometheus
