global:
  postgresql:
    auth:
      username: things
      database: things

image:
  registry: docker.io
  repository: rafttech/things
  tag: ""

config:
  owner: ""
  updateCount: 10
  waitDuration: 10s

topologuSpreadConstraints: {}
nodeSelector: {}

dbInitJob:
  enabled: true
  command:
    - /opt/bitnami/postgresql/bin/psql
    - $(PG_CONNECTION)
  args:
    - "--file"
    - "/config/schema.sql"
  # If unset, the default postgresql image will be used
  image:
    registry:
    repository:
    tag:
  initContainer:
    enabled: true
    command:
      - /bin/bash
    args:
      - "-c"
      - "while ! pg_isready -d $(PG_CONNECTION); do echo waiting for database to be come ready; sleep 5; done"
    # If unset, the default postgresql image will be used
    image:
      registry:
      repository:
      tag:
      
postgresql:
  enabled: true
  auth:
    username:
    password:
    service:
    connection: postgres://$(PG_USERNAME):$(PG_password)@$(PG_SERVICE)/$(PG_DATABASE)
    secretRef: things-postgresql
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
