global:
  postgresql:
    auth:
      username: things
      database: things

image:
  registry: docker.io
  repository: rafttech/things
  tag: ""

config:
  owner: ""
  updateCount: 10
  waitDuration: 10s

topologuSpreadConstraints: {}
nodeSelector: {}

postgresql:
  auth:
    username:
    password:
    service:
    connection: postgres://$(PG_USERNAME):$(PG_password)@$(PG_SERVICE)/$(PG_DATABASE)
    secretRef: things-postgresql
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
