{{- if .Values.client.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "syncd.clientFullname" . }}
  labels:
    {{- include "syncd.clientLabels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
data:
  client.yaml: |
    {{- with .Values.logging }}
    logging:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    client:
      name: {{ default .Values.client.name .Release.Name }}
      metrics:
        listen: ":8080"
      auth:
        {{- if .Values.auth.preSharedKey.enabled }}
        preSharedKey:
          fromEnv: SYNCD_AUTH_PRESHARED_KEY
        {{- end }}
        {{- include "syncd.tlsConfig" .Values.client.tls | nindent 8 }}
      peers:
        {{- toYaml .Values.client.peers | nindent 8 }}

    {{- include "syncd.graphConfig" . | nindent 4 }}
    {{- end }}