{{- if .Values.client.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "syncd.clientFullname" . }}
  labels:
    {{- include "syncd.clientLabels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
data:
  client.yaml: |
    {{- with .Values.logging }}
    logging:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    client:
      metrics:
        listen: ":8081"
      {{- include "syncd.tlsConfig" .Values.client.tls | nindent 6 }}
      auth:
        {{- if .Values.auth.preSharedKey.enabled }}
        preSharedKey:
          fromEnv: SYNCD_AUTH_PRESHARED_KEY
        {{- else }} { }
        {{- end }}
      peers:
        {{- toYaml .Values.client.peers}}

    {{- include "syncd.graphConfig" . | nindent 4 }}
  {{- end }}