{{- if .Values.client.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncd.clientFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syncd.clientLabels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "syncd.clientSelectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: http-metrics
      port: 8081
      protocol: TCP
{{- end }}