{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "syncd.clientFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syncd.clientLabels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "syncd.clientSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}