{{- if .Values.server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "syncd.serverFullname" . }}
  labels:
    {{- include "syncd.serverLabels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
data:
  server.yaml: |
    {{- with .Values.logging }}
    logging:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    server:
      listen: {{- if .Values.server.tls.enabled }} ":8443" {{- else }} ":8080" {{- end }}
      metrics:
        listen: ":8081"
      {{- include "syncd.tlsConfig" .Values.server.tls | nindent 6 }}
      auth:
        {{- if .Values.auth.preSharedKey.enabled }}
        preSharedKey:
          fromEnv: SYNCD_AUTH_PRESHARED_KEY
        {{- else }} {}
        {{- end }}
      models:
        {{- toYaml .Values.server.models | nindent 8 }}

    {{- include "syncd.graphConfig" . | nindent 4 }}
  {{- end }}