{{- $hasSecret := not .Values.graph.source.postgres.connection.fromPreExistingSecret }}
{{- $hasSecret = or $hasSecret (and .Values.auth.preSharedKey.enabled (not .Values.auth.preSharedKey.fromExistingSecret)) }}
{{- if and .Values.server.enabled $hasSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "syncd.serverFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syncd.serverLabels" .  | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
data:
  {{- if and .Values.auth.preSharedKey.enabled (not .Values.auth.preSharedKey.fromExistingSecret) }}
  AUTH_PRESHARED_KEY: {{ .Values.auth.preSharedKey.value | b64enc }}
  {{- end }}
  {{- if not .Values.graph.source.postgres.connection.fromPreExistingSecret}}
  {{- with .Values.graph.source.postgres.connection.values }}
  POSTGRES_HOST: {{ .host | b64enc }}
  POSTGRES_USERNAME: {{ .username | b64enc }}
  POSTGRES_PASSWORD: {{ .password | b64enc }}
  POSTGRES_DATABASE: {{ .database | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}