apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "things.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "things.labels" . | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- include "things.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "things.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "things"
          image: {{ default .Values.image.registry .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ default .Values.image.tag .Chart.AppVersion }}
          command:
            - /things
          args:
            - -w
            - {{ .Values.config.waitDuration }}
            - -n
            - {{ .Values.config.updateCount | quote }}
            - --metrics
            - ":8080"
            - {{ default .Values.config.owner (printf "%s-%s" .Release.Namespace .Release.Name) }}
          env:
            - name: POSTGRES_USERNAME
              value: {{ .Values.global.postgresql.auth.username }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.global.postgresql.auth.database }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{.Values.global.postgresql.auth.secretRef }}
            - name: SYNCD_THINGS_CONN
              value: postgres://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@{{ .Release.Name }}-postgresql:5432/$(POSTGRES_DATABASE)
          livenessProbe:
            httpGet:
              port: http-metrics
              path: /healthz
          readinessProbe:
            httpGet:
              port: http-metrics
              path: /healthz/readz
          ports:
            - containerPort: 8080
              name: http-metrics
  strategy:
    type: Recreate

{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PodMonitor" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "things.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "things.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podMetricsEndpoints:
    - port: http-metrics
  selector:
    matchLabels:
      {{- include "things.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}