name: Go Build

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
    tags: ["*"]
  pull_request:
    branches: [ "develop" ]

permissions: read-all

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          cache: true
          go-version-file: 'go.mod'
      - name: Install Dependencies
        run: go get .
      - name: Verify
        run: go vet ./...
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          cache: true
          go-version-file: 'go.mod'
      - name: Vet
        run: go vet ./...
#      - name: Unit Tests
#        run: go test ./... -short -timeout 15s
  Release:
    needs: Test
    runs-on: ubuntu-latest
    if:  github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up QEMU  # Virtualization tool  
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      
      - name: Login to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push syncd snapshot
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          push: true
          tags: rafttech/syncd:${{ github.sha }}

      - name: Build and push things snapshot
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          file: examples/things/app/Dockerfile
          push: true
          tags: rafttech/things:${{ github.sha }}

      - name: set RELEASE_VERSION 
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build and push syncd release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          push: true
          tags: rafttech/syncd:${{ env.RELEASE_VERSION }}

      - name: Build and push things release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          file: examples/things/app/Dockerfile
          push: true
          tags: rafttech/things:${{ env.RELEASE_VERSION }}